package entity;
// Generated Aug 21, 2017 12:30:08 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DeliveryCost generated by hbm2java
 */
public class DeliveryCost  implements java.io.Serializable {


     private Integer delId;
     private String zoneName;
     private double delCost;
     private Set productOrders = new HashSet(0);

    public DeliveryCost() {
    }

	
    public DeliveryCost(String zoneName, double delCost) {
        this.zoneName = zoneName;
        this.delCost = delCost;
    }
    public DeliveryCost(String zoneName, double delCost, Set productOrders) {
       this.zoneName = zoneName;
       this.delCost = delCost;
       this.productOrders = productOrders;
    }
   
    public Integer getDelId() {
        return this.delId;
    }
    
    public void setDelId(Integer delId) {
        this.delId = delId;
    }
    public String getZoneName() {
        return this.zoneName;
    }
    
    public void setZoneName(String zoneName) {
        this.zoneName = zoneName;
    }
    public double getDelCost() {
        return this.delCost;
    }
    
    public void setDelCost(double delCost) {
        this.delCost = delCost;
    }
    public Set getProductOrders() {
        return this.productOrders;
    }
    
    public void setProductOrders(Set productOrders) {
        this.productOrders = productOrders;
    }




}


