package entity;
// Generated Aug 21, 2017 12:30:08 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SubCat generated by hbm2java
 */
public class SubCat  implements java.io.Serializable {


     private Integer subCatId;
     private Category category;
     private String subCatName;
     private String subCatDesc;
     private Set products = new HashSet(0);

    public SubCat() {
    }

	
    public SubCat(Category category, String subCatName, String subCatDesc) {
        this.category = category;
        this.subCatName = subCatName;
        this.subCatDesc = subCatDesc;
    }
    public SubCat(Category category, String subCatName, String subCatDesc, Set products) {
       this.category = category;
       this.subCatName = subCatName;
       this.subCatDesc = subCatDesc;
       this.products = products;
    }
   
    public Integer getSubCatId() {
        return this.subCatId;
    }
    
    public void setSubCatId(Integer subCatId) {
        this.subCatId = subCatId;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getSubCatName() {
        return this.subCatName;
    }
    
    public void setSubCatName(String subCatName) {
        this.subCatName = subCatName;
    }
    public String getSubCatDesc() {
        return this.subCatDesc;
    }
    
    public void setSubCatDesc(String subCatDesc) {
        this.subCatDesc = subCatDesc;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


