package entity;
// Generated Aug 21, 2017 12:30:08 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserRoll generated by hbm2java
 */
public class UserRoll  implements java.io.Serializable {


     private Integer rollId;
     private String rollName;
     private Set users = new HashSet(0);

    public UserRoll() {
    }

	
    public UserRoll(String rollName) {
        this.rollName = rollName;
    }
    public UserRoll(String rollName, Set users) {
       this.rollName = rollName;
       this.users = users;
    }
   
    public Integer getRollId() {
        return this.rollId;
    }
    
    public void setRollId(Integer rollId) {
        this.rollId = rollId;
    }
    public String getRollName() {
        return this.rollName;
    }
    
    public void setRollName(String rollName) {
        this.rollName = rollName;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


