package entity;
// Generated Aug 21, 2017 12:30:08 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private UserRoll userRoll;
     private String userName;
     private String userPass;
     private String email;
     private Date regiDate;
     private String contract;
     private Set productOrders = new HashSet(0);

    public User() {
    }

	
    public User(UserRoll userRoll, String userName, String userPass, String email, Date regiDate, String contract) {
        this.userRoll = userRoll;
        this.userName = userName;
        this.userPass = userPass;
        this.email = email;
        this.regiDate = regiDate;
        this.contract = contract;
    }
    public User(UserRoll userRoll, String userName, String userPass, String email, Date regiDate, String contract, Set productOrders) {
       this.userRoll = userRoll;
       this.userName = userName;
       this.userPass = userPass;
       this.email = email;
       this.regiDate = regiDate;
       this.contract = contract;
       this.productOrders = productOrders;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public UserRoll getUserRoll() {
        return this.userRoll;
    }
    
    public void setUserRoll(UserRoll userRoll) {
        this.userRoll = userRoll;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPass() {
        return this.userPass;
    }
    
    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getRegiDate() {
        return this.regiDate;
    }
    
    public void setRegiDate(Date regiDate) {
        this.regiDate = regiDate;
    }
    public String getContract() {
        return this.contract;
    }
    
    public void setContract(String contract) {
        this.contract = contract;
    }
    public Set getProductOrders() {
        return this.productOrders;
    }
    
    public void setProductOrders(Set productOrders) {
        this.productOrders = productOrders;
    }




}


